name: cyphal_init.sh

on: [push]
jobs:
  cyphal_init:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Install basic dependencies
        run: |
          sudo apt-get update
          python3 -m pip install pip -U

      - name: Install dependencies
        run: ./scripts/ubuntu.sh --yes --cyphal-only

      - name: Check scripts/cyphal/init.sh and Yakut 
        run: |
          pwd
          ls -l
          source scripts/cyphal/init.sh -i slcan0 -n 127 -v
          timeout --verbose --preserve-status 3 y mon > yakut_output.txt || true
          cat yakut_output.txt
